In [78]:
import numpy as np
import pandas as pd
dataset = pd.read_csv('C:/Users/HP/Downloads/Cleaned-Data project.csv')
dataset


Menstrual_Irregularity Stress_Level           Age
0                      Yes           No         20-25
1                       No           No  Less than 20
2                       No          Yes  Less than 20
3                       No          Yes         20-25
4                       No          Yes  Less than 20
..                     ...          ...           ...
168                     No           No  Less than 20
169                    Yes          Yes         20-25
170                    Yes           No         20-25
171                    Yes          Yes  Less than 20
172                    Yes          Yes         20-25

[173 rows x 3 columns]

In [79]:
print(dataset.columns)

Index(['Menstrual_Irregularity', 'Stress_Level', 'Age'], dtype='object')


In [80]:
x=dataset[['Menstrual_Irregularity', 'Stress_Level', 'Age']].values
x

array([['Yes', 'No', '20-25'],
       ['No', 'No', 'Less than 20'],
       ['No', 'Yes', 'Less than 20'],
       ['No', 'Yes', '20-25'],
       ['No', 'Yes', 'Less than 20'],
       ['Yes', 'Yes', 'Less than 20'],
       ['Yes', 'Yes', '20-25'],
       ['No', 'Yes', 'Less than 20'],
       ['Yes', 'Yes', '20-25'],
       ['Yes', 'Yes', '20-25'],
       ['No', 'Yes', '20-25'],
       ['Yes', 'Yes', '20-25'],
       ['Yes', 'Yes', 'Less than 20'],
       ['Yes', 'Yes', '20-25'],
       ['Yes', 'Yes', '20-25'],
       ['Yes', 'Yes', '20-25'],
       ['No', 'Yes', 'Less than 20'],
       ['No', 'Yes', 'Less than 20'],
       ['Yes', 'Yes', '20-25'],
       ['No', 'Yes', 'Less than 20'],
       ['No', 'Yes', 'Less than 20'],
       ['Yes', 'Yes', '20-25'],
       ['No', 'Yes', '20-25'],
       ['Yes', 'Yes', '45 and above'],
       ['Yes', 'Yes', '20-25'],
       ['Yes', 'Yes', '45 and above'],
       ['Yes', 'Yes', 'Less than 20'],
       ['No', 'Yes', 'Less than 20'],
       ['Yes', 'Yes'

In [81]:
y=dataset[['Stress_Level']].values
y

array([['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['No'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
   

In [82]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
import numpy as np
x= np.array([
             [1,'Yes',3],
             [2,'No',np.nan],
             [3,'Yes',6],
             [4,np.nan,8]
             ],dtype=object)
label_encoder=LabelEncoder()
x[:,1]=label_encoder.fit_transform(x[:,1].astype(str))
x=x.astype(float)
imputer=SimpleImputer(missing_values=np.nan,
                      strategy='mean')
x[:,1:3]=imputer.fit_transform(x[:,
                                 1:3])
print(x)

[[1.         1.         3.        ]
 [2.         0.         5.66666667]
 [3.         1.         6.        ]
 [4.         2.         8.        ]]


In [83]:
from sklearn.preprocessing import LabelEncoder
import numpy as np
label_encoder_x = LabelEncoder()
x= np.array([[0,2,1,2,1,0,2,0,1,0]])
x_transform = label_encoder_x.fit_transform(x[:,0])
print(x_transform)

[0]


In [84]:
x[:,0] = label_encoder.fit_transform(x[:,0])
x

array([[0, 2, 1, 2, 1, 0, 2, 0, 1, 0]])

In [85]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
OneHotencoder = OneHotEncoder()
x=OneHotencoder.fit_transform(dataset.Menstrual_Irregularity.values.reshape(-1,1)).toarray()
x 

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.

In [86]:
label_encoder_y= LabelEncoder()
y=label_encoder_y.fit_transform(y)
y

C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1])

In [87]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.

In [88]:
x_test

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [89]:
y_train

array([1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1])

In [90]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [91]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)
x_train

array([[ 1.14017543, -1.14017543],
       [-0.87705802,  0.87705802],
       [ 1.14017543, -1.14017543],
       [ 1.14017543, -1.14017543],
       [-0.87705802,  0.87705802],
       [-0.87705802,  0.87705802],
       [ 1.14017543, -1.14017543],
       [-0.87705802,  0.87705802],
       [ 1.14017543, -1.14017543],
       [-0.87705802,  0.87705802],
       [ 1.14017543, -1.14017543],
       [-0.87705802,  0.87705802],
       [-0.87705802,  0.87705802],
       [ 1.14017543, -1.14017543],
       [ 1.14017543, -1.14017543],
       [-0.87705802,  0.87705802],
       [-0.87705802,  0.87705802],
       [ 1.14017543, -1.14017543],
       [ 1.14017543, -1.14017543],
       [ 1.14017543, -1.14017543],
       [ 1.14017543, -1.14017543],
       [-0.87705802,  0.87705802],
       [ 1.14017543, -1.14017543],
       [ 1.14017543, -1.14017543],
       [-0.87705802,  0.87705802],
       [-0.87705802,  0.87705802],
       [ 1.14017543, -1.14017543],
       [-0.87705802,  0.87705802],
       [-0.87705802,

In [92]:
x_test

array([[ 1.38443731, -1.38443731],
       [-0.72231512,  0.72231512],
       [ 1.38443731, -1.38443731],
       [-0.72231512,  0.72231512],
       [-0.72231512,  0.72231512],
       [ 1.38443731, -1.38443731],
       [ 1.38443731, -1.38443731],
       [-0.72231512,  0.72231512],
       [ 1.38443731, -1.38443731],
       [ 1.38443731, -1.38443731],
       [-0.72231512,  0.72231512],
       [ 1.38443731, -1.38443731],
       [-0.72231512,  0.72231512],
       [ 1.38443731, -1.38443731],
       [-0.72231512,  0.72231512],
       [-0.72231512,  0.72231512],
       [-0.72231512,  0.72231512],
       [-0.72231512,  0.72231512],
       [-0.72231512,  0.72231512],
       [-0.72231512,  0.72231512],
       [-0.72231512,  0.72231512],
       [-0.72231512,  0.72231512],
       [ 1.38443731, -1.38443731],
       [ 1.38443731, -1.38443731],
       [-0.72231512,  0.72231512],
       [-0.72231512,  0.72231512],
       [-0.72231512,  0.72231512],
       [-0.72231512,  0.72231512],
       [ 1.38443731,